# Module 2: Exercise

>__Task 1__
>
>Import pandas and NumPy libraries using their alias

In [304]:
import pandas as pd
import numpy as np

## Python Native Data Types

### Numbers, Strings, Booleans

>__Task 2__
>
>Perform the following operations and return to see the results
>- $3+2\times4$
>- $(3+2)\div4$
>- $(3+2)^4$
>- get the integer quotient of $(3+2)/4$ using floor division

In [309]:
(3 * 2)+4

10

In [311]:
(3 + 2)/4

1.25

In [313]:
(3 + 2)**4

625

In [315]:
(3 + 2)//4

1

Note __the floor division rounds the result to the nearest whole number__.

>__Task 3__
>
>Run the following cells and find the data type of each object

In [319]:
4//7

0

In [321]:
# Return data type
type(4//7)

int

In [323]:
a = 11/(-3)

In [325]:
# Return data type
type(a)

float

In [327]:
b = True
# Return data type
type(b)

bool

>__Task 4__
>
>Assume your student ID is 00223298, assign it to a variable as a string object

In [330]:
id = '00223298'
# Return data type
type(id)

str

>__Task 5__
>
>Convert the variable __c__ below to float

In [333]:
c = '6.0'
# Convert to float
c = float(c)


In [335]:
# Return data type
type(c)

float

>__Task 6__
>
>Run the cell below to get the value of variable __d__ and then convert it to integer

In [338]:
d = (-6) < 78
d

True

In [340]:
# Convert to integer
d = int(d)

In [342]:
# Return data type
type(d)

int

### Lists, Tuples, Sets

>__Task 7__
>
>Create a list, a tuple, and a set containing the following elements and compare the outputs:
>
>`0`, `robot` (str), `-9`, `False` (bool), `77`, `77`, `100`, `true` (str)

In [346]:
# Create a list
l = [0,"robot",-9,False,77,77,100,"true"]
l

[0, 'robot', -9, False, 77, 77, 100, 'true']

In [348]:
# Return data type
type(l)

list

In [350]:
# Create a tuple
t = (0,"robot",-9,False,77,77,100,"true")
t

(0, 'robot', -9, False, 77, 77, 100, 'true')

In [352]:
# Return data type
type(t)

tuple

In [354]:
# Create a set
s = {0,"robot",-9,False,77,77,100,"true"}
s

{-9, 0, 100, 77, 'robot', 'true'}

In [356]:
# Return data type
type(s)

set

>__Task 8__
>
>Overwrite the element `true` to `1` in the above list __l__

In [359]:
l = [0,"robot",-9,False,77,77,100,"true"]
i = l.index('true')
l = l[:i]+[1]+l[i+1:]
l

[0, 'robot', -9, False, 77, 77, 100, 1]

>__Task 9__
>
>Add `age` and `weight` to the list __e__ below using __`+`__

In [362]:
e = ['diabetes', 'heart bypass'] + ["age", "weight"]
e

['diabetes', 'heart bypass', 'age', 'weight']

In [364]:
f = ['diabetes', 'heart bypass'] + ["age", "weight"]
f

['diabetes', 'heart bypass', 'age', 'weight']

Alternatively, you can use the __`extend()`__ method to add item(s) to the end of the list:

In [367]:
e.extend(['age', 'weight'])
e

['diabetes', 'heart bypass', 'age', 'weight', 'age', 'weight']

### Dictionaries

In [370]:
cities = {'Australia' :['Sydney', 'Melbourne', 'Canberra'],
          'Canada'    :['Toronto', 'Montreal', 'Ottawa'],
          'Germany'   :['Berlin', 'Hamburg', 'Munich'],
          'Japan'     :['Tokyo', 'Osaka', 'Nagoya']}
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya']}

>__Task 10__
>
>Return only values of the `Japan` key

In [373]:
cities['Japan']

['Tokyo', 'Osaka', 'Nagoya']

>__Task 11__
>
>Return only values and only keys of the dictionary __cities__

In [376]:
# Return only values
cities.values()

dict_values([['Sydney', 'Melbourne', 'Canberra'], ['Toronto', 'Montreal', 'Ottawa'], ['Berlin', 'Hamburg', 'Munich'], ['Tokyo', 'Osaka', 'Nagoya']])

In [378]:
# Return only keys
cities.keys()

dict_keys(['Australia', 'Canada', 'Germany', 'Japan'])

You can use a __`for`__ loop to print not only keys but also the values corresponding to that keys:

In [381]:
for k in cities.keys():
    print('key: ', k, '\nvalue: ', cities[k], '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



>__Task 12__
>
>Return the same output above using the __`items()`__ method within a `for` loop

In [384]:
for i, j in cities.items():
    print(i, j)

Australia ['Sydney', 'Melbourne', 'Canberra']
Canada ['Toronto', 'Montreal', 'Ottawa']
Germany ['Berlin', 'Hamburg', 'Munich']
Japan ['Tokyo', 'Osaka', 'Nagoya']


Task 13
Add `Egypt` as a new key to cities and `Cairo`, `Durban`, `Alexandria` as its corresponding values


In [387]:
cities["Egypt"] = ["Cairo", "Durban", "Alexandria"]
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Durban', 'Alexandria']}

>__Task 14__
>
>`Durban` is actually in South Africa. Overwrite it with `Giza` and then confirm values of the __Egypt__ column

In [390]:
cities["Egypt"][1] = "Giza"
for i in cities.items():
    print(i)

('Australia', ['Sydney', 'Melbourne', 'Canberra'])
('Canada', ['Toronto', 'Montreal', 'Ottawa'])
('Germany', ['Berlin', 'Hamburg', 'Munich'])
('Japan', ['Tokyo', 'Osaka', 'Nagoya'])
('Egypt', ['Cairo', 'Giza', 'Alexandria'])


>__Task 15__
>
>Delete the key `Germany` from __cities__ 

In [393]:
del cities['Germany']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

## NumPy Arrays

>__Task 16__
>
>Create an array that contains a list of `99`, `2`, `65`

In [397]:
arr = [99, 2, 65]
arr

[99, 2, 65]

>__Task 17__
>
>Run the following operations to see the results

In [400]:
# Natural logarithm
np.log(arr)

array([4.59511985, 0.69314718, 4.17438727])

In [402]:
# Square root
np.sqrt(arr)

array([9.94987437, 1.41421356, 8.06225775])

In [404]:
# Cosine
np.cos(arr)

array([ 0.03982088, -0.41614684, -0.56245385])

We can use the __`arange()`__ method to create an array from 0 to any number of values we want. For example, we want an array of 20 numbers, we write:

In [407]:
num1 = np.arange(20)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

>__Task 18__
>
>Retrieve the first 5 numbers of the above array __num1__

In [410]:
print(num1[slice(5)])

[0 1 2 3 4]


We can also pass the __`reshape()`__ function with `arange()` to specify rows and columns. For example, we can rearrange the above array into 5 rows and 4 columns:

In [413]:
num2 = np.arange(20).reshape(5,4)
num2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

>__Task 19__
>
>Retrieve the numbers from the last 2 rows and first 3 columns in the array __num2__ (your output should return `[12, 13, 14], [16, 17, 18]`)

In [416]:
num2 = np.arange(20).reshape(5,4)
print(num2[-2:, :3])

[[12 13 14]
 [16 17 18]]


## Pandas Series and DataFrames

>__Task 20__
>
>Import the data file "bank_data.csv"

In [420]:
bank = pd.read_csv('bank_data.csv')
bank

age            job  marital  education default  balance housing loan  \
0     30.0     unemployed  married    primary      no   1787.0      no   no   
1     33.0       services  married  secondary      no   4789.0     yes  yes   
2     35.0     management   single   tertiary      no   1350.0     yes   no   
3     30.0     management  married   tertiary      no      NaN     yes  yes   
4     59.0    blue-collar  married  secondary      no      0.0     yes   no   
...    ...            ...      ...        ...     ...      ...     ...  ...   
4516  33.0       services  married  secondary      no   -333.0     yes   no   
4517  57.0  self-employed  married   tertiary     yes  -3313.0     yes  yes   
4518  57.0     technician  married  secondary      no    295.0      no   no   
4519  28.0    blue-collar  married  secondary      no   1137.0      no   no   
4520  44.0   entrepreneur   single   tertiary      no   1136.0     yes  yes   

       contact   day  month  duration  campaign  pdays  previous poutcome   y  \
0     cellular  19.0     10      79.0       1.0   -1.0       0.0  unknown  no   
1     cellular  11.0      5     220.0       1.0  339.0       4.0  failure  no   
2     cellular  16.0      4     185.0       1.0  330.0       1.0  failure  no   
3          NaN   3.0      6     199.0       4.0   -1.0       0.0  unknown  no   
4          NaN   5.0      5     226.0       1.0   -1.0       0.0  unknown  no   
...        ...   ...    ...       ...       ...    ...       ...      ...  ..   
4516  cellular  30.0      7     329.0       5.0   -1.0       0.0  unknown  no   
4517       NaN   9.0      5     153.0       1.0   -1.0       0.0  unknown  no   
4518  cellular  19.0      8     151.0      11.0   -1.0       0.0  unknown  no   
4519  cellular   6.0      2     129.0       4.0  211.0       3.0    other  no   
4520  cellular   3.0      4     345.0       2.0  249.0       7.0    other  no   

      year  
0     2022  
1     2022  
2     2022  
3     2022  
4     2022  
...    ...  
4516  2022  
4517  2022  
4518  2022  
4519  2022  
4520  2022  

[4521 rows x 18 columns]

>__Task 21__
>
>Select __age__ column as a series and confirm the result by checking its data type

In [423]:
age_col = bank['age']
age_col

0       30.0
1       33.0
2       35.0
3       30.0
4       59.0
        ... 
4516    33.0
4517    57.0
4518    57.0
4519    28.0
4520    44.0
Name: age, Length: 4521, dtype: float64

In [425]:
# Return data type
age_col.dtype

dtype('float64')

Notice that __`df[...]` returns a series and `df[[...]]` returns a data frame__.

>__Task 22__
>
>Select columns __job__, __education__, and __balance__ as a data frame and confirm the result by checking its data type

In [429]:
colums = bank[['job','education','balance']]
colums

job  education  balance
0        unemployed    primary   1787.0
1          services  secondary   4789.0
2        management   tertiary   1350.0
3        management   tertiary      NaN
4       blue-collar  secondary      0.0
...             ...        ...      ...
4516       services  secondary   -333.0
4517  self-employed   tertiary  -3313.0
4518     technician  secondary    295.0
4519    blue-collar  secondary   1137.0
4520   entrepreneur   tertiary   1136.0

[4521 rows x 3 columns]

In [431]:
# Return data type
colums.dtypes

job           object
education     object
balance      float64
dtype: object

>__Task 23__
>
>Retrieve the last 7 rows and first 5 columns from the __bank__ data

In [434]:
last_7_first_5 = bank.iloc[-7:, :5]
last_7_first_5

age            job  marital  education default
4514  38.0    blue-collar  married  secondary      no
4515  32.0       services   single  secondary      no
4516  33.0       services  married  secondary      no
4517  57.0  self-employed  married   tertiary     yes
4518  57.0     technician  married  secondary      no
4519  28.0    blue-collar  married  secondary      no
4520  44.0   entrepreneur   single   tertiary      no

### Dates and Times

Let's create a new column of the client contact dates using the __bank__ data:

In [438]:
bank['contact_date'] = bank['year'].astype(str)+'-'+bank['month'].astype(str)+'-'+bank['day'].astype(int).astype(str)
bank['contact_date']

0       2022-10-19
1        2022-5-11
2        2022-4-16
3         2022-6-3
4         2022-5-5
           ...    
4516     2022-7-30
4517      2022-5-9
4518     2022-8-19
4519      2022-2-6
4520      2022-4-3
Name: contact_date, Length: 4521, dtype: object

The last line above shows that the dtype (data type) is a generic object, not a datetime type.

>__Task 24__
>
>Convert the __contact_date__ column to a datetime object

In [442]:
bank['contact_date'] = pd.to_datetime(bank['contact_date'])
bank['contact_date']

0      2022-10-19
1      2022-05-11
2      2022-04-16
3      2022-06-03
4      2022-05-05
          ...    
4516   2022-07-30
4517   2022-05-09
4518   2022-08-19
4519   2022-02-06
4520   2022-04-03
Name: contact_date, Length: 4521, dtype: datetime64[ns]

Now, it is properly read as date.

## Data Manipulation

In [446]:
import warnings
warnings.filterwarnings("ignore")

>__Task 25__
>
>Import the data file "hc_train.csv" and explore the first 5 rows

In [449]:
hc = pd.read_csv("hc_train.csv")
hc

Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital          Department Ward_Type  \
0                                      3          gynecology         R   
1                                      4          gynecology         Q   
2                                      4          gynecology         S   
3                                      2          anesthesia         S   
4                                      3          gynecology         R   
...                                  ...                 ...       ...   
51233                                  3          gynecology         Q   
51234                                  4          gynecology         Q   
51235                                  3          gynecology         S   
51236                                  4          gynecology         R   
51237                                  2  TB & Chest disease         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme                      4  51-6

>__Task 26__
>
>Convert the values of the __Department__ column to uppercase

In [452]:
hc['Department'].str.upper()

0                GYNECOLOGY
1                GYNECOLOGY
2                GYNECOLOGY
3                ANESTHESIA
4                GYNECOLOGY
                ...        
51233            GYNECOLOGY
51234            GYNECOLOGY
51235            GYNECOLOGY
51236            GYNECOLOGY
51237    TB & CHEST DISEASE
Name: Department, Length: 51238, dtype: object

### Replace Values

>__Task 27__
>
>Replace `TB & Chest disease` in the __Department__ column with `Tuberculosis & Chest`

In [456]:
hc['Department'] = hc['Department'].replace({'TB': 'Tuberculosis', 'Chest disease': 'Chest'})

# Print unique variables in the column to confirm the change 
hc['Department'].unique()

array(['gynecology', 'anesthesia', 'radiotherapy', 'surgery',
       'TB & Chest disease'], dtype=object)

We can also replace with different values by passing a list or dict as substitutes.

>__Task 28__
>
>Replace values in the __Severity of Illness__ column with a dictionary that maps variables below:
>
>- Extreme: '3rd degree'
>- Moderate: '2nd degree'
>- Minor: '1st degree'

In [460]:
# Creat a dict
map_dict = {'Extreme': '3rd Degree',
            'Moderate':'2rd Degree',
            'Minor': '1st Degree'}

# Replace values with the dict
hc['Severity of Illness'] = hc['Severity of Illness'].replace(map_dict)
hc

Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital          Department Ward_Type  \
0                                      3          gynecology         R   
1                                      4          gynecology         Q   
2                                      4          gynecology         S   
3                                      2          anesthesia         S   
4                                      3          gynecology         R   
...                                  ...                 ...       ...   
51233                                  3          gynecology         Q   
51234                                  4          gynecology         Q   
51235                                  3          gynecology         S   
51236                                  4          gynecology         R   
51237                                  2  TB & Chest disease         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
0             Emergency          1st Degree                      2  11-20   
1             Emergency          3rd Degree                      4  31-40   
2                Trauma          2rd Degree                      6  71-80   
3                Urgent          3rd Degree                      2  71-80   
4                Trauma          2rd Degree                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma          1st Degree                      2  21-30   
51234         Emergency          2rd Degree                      2  51-60   
51235         Emergency          2rd Degree                     10  51-60   
51236            Trauma          1st Degree                      2  21-30   
51237            Trauma          3rd Degree                      4  51-6

### Rename Column and Row Labels

>__Task 29__
>
>Rename all column headings to their lowercase values by passing a `str` function

In [464]:
hc.columns = hc.columns.str.lower()
hc

unnamed: 0  case_id  hospital_code hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital          department ward_type  \
0                                      3          gynecology         R   
1                                      4          gynecology         Q   
2                                      4          gynecology         S   
3                                      2          anesthesia         S   
4                                      3          gynecology         R   
...                                  ...                 ...       ...   
51233                                  3          gynecology         Q   
51234                                  4          gynecology         Q   
51235                                  3          gynecology         S   
51236                                  4          gynecology         R   
51237                                  2  TB & Chest disease         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission severity of illness  visitors with patient    age  \
0             Emergency          1st Degree                      2  11-20   
1             Emergency          3rd Degree                      4  31-40   
2                Trauma          2rd Degree                      6  71-80   
3                Urgent          3rd Degree                      2  71-80   
4                Trauma          2rd Degree                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma          1st Degree                      2  21-30   
51234         Emergency          2rd Degree                      2  51-60   
51235         Emergency          2rd Degree                     10  51-60   
51236            Trauma          1st Degree                      2  21-30   
51237            Trauma          3rd Degree                      4  51-6

>__Task 30__
>
>Rename the column headings below using a dictionary that maps
>
>- `Severity of Illness` to `Severity`
>- `case_id` to `ID`

In [467]:
df = pd.DataFrame(hc)

col_dict = {'severity of illness' : 'Severity',
            'case_id' : 'ID'}
df.rename(columns=col_dict, inplace=True)
df.update(hc)
df

unnamed: 0      ID  hospital_code hospital_type_code  \
0          119967  119968             27                  a   
1           92433   92434              6                  a   
2          132258  132259             16                  c   
3          168439  168440             23                  a   
4           82100   82101             25                  e   
...           ...     ...            ...                ...   
51233      289419  289420             10                  e   
51234      285283  285284             11                  b   
51235       79117   79118              9                  d   
51236      128901  128902             23                  a   
51237      210970  210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital          department ward_type  \
0                                      3          gynecology         R   
1                                      4          gynecology         Q   
2                                      4          gynecology         S   
3                                      2          anesthesia         S   
4                                      3          gynecology         R   
...                                  ...                 ...       ...   
51233                                  3          gynecology         Q   
51234                                  4          gynecology         Q   
51235                                  3          gynecology         S   
51236                                  4          gynecology         R   
51237                                  2  TB & Chest disease         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission    Severity  visitors with patient    age  \
0             Emergency  1st Degree                      2  11-20   
1             Emergency  3rd Degree                      4  31-40   
2                Trauma  2rd Degree                      6  71-80   
3                Urgent  3rd Degree                      2  71-80   
4                Trauma  2rd Degree                      3  61-70   
...                 ...         ...                    ...    ...   
51233            Trauma  1st Degree                      2  21-30   
51234         Emergency  2rd Degree                      2  51-60   
51235         Emergency  2rd Degree                     10  51-60   
51236            Trauma  1st Degree                      2  21-30   
51237            Trauma  3rd Degree                      4  51-60   

       admission_deposit                stay  
0                 5072.0               21-30  
1       

### Binning Methods

>__Task 31__
>
>Group the case IDs into three categories below:
>
>- (0, 100000) to `old case`
>- (100001-200000) to `recent case`
>- (200001-last) to `new case`

In [471]:
# Check the maximum value of the column
hc['case_id'].max()

318438

In [473]:
df = pd.DataFrame(hc)

def case(case_id):
    if 0 <= case_id <= 100000:
        return 'old case'
    elif 100001 <= case_id <= 200000:
        return 'recent case'
    else:
        return 'new case'

df["case level"] = df["case_id"].apply(case)

>__Task 32__
>
>Group the case IDs into to 3 equal-sized bins with 4 decimal places

In [476]:
group_equ =hc['case_id']
pd.cut(ID, 3, precision= 4)
group_equ

0        119968
1         92434
2        132259
3        168440
4         82101
          ...  
51233    289420
51234    285284
51235     79118
51236    128902
51237    210971
Name: case_id, Length: 51238, dtype: int64

>__Task 33__
>
>Group the case IDs into 4 quartiles with 2 decimal places

In [479]:
group_qua = pd.qcut(ID, 3, precision=2)
group_qua

0        (106907.0, 212651.0]
1            (0.99, 106907.0]
2        (106907.0, 212651.0]
3        (106907.0, 212651.0]
4            (0.99, 106907.0]
                 ...         
51233    (212651.0, 318438.0]
51234    (212651.0, 318438.0]
51235        (0.99, 106907.0]
51236    (106907.0, 212651.0]
51237    (106907.0, 212651.0]
Name: case_id, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(0.99, 106907.0] < (106907.0, 212651.0] < (212651.0, 318438.0]]

### Random Sampling

>__Task 34__
>
>Randomly select 10 data points from the __hc__ data without repeat elements

In [483]:
values = sample_nums.values.flatten()
unique_val = pd.Series(values).drop_duplicates()

random_values = pd.Series(unique_val).sample(n=10, random_state=1)
print(random_values.values)

[132196 143254 282521 17238 250926 193169 60571 87716 21325 41129]


>__Task 35__
>
>Randomly select 50 data points from the __patientid__ column allowing repeat elements

In [486]:
random_points = np.random.choice(df['patientid'], size=50, replace=True)
print(random_points)

[ 46768 101104  92442  93437  40779  76781 107281 126645 115693    158
  97484  28234  19137   1710  64240 107454    970 108344 114406  85320
  65191  69430  87627  75514 117405  59625  59285  48229 122511  18194
  69943   7553  96895  11248  97288  47202 102389  46052  14985  40113
 112119  43954  61744  39098  89208  51375 130927  27148   6069 129582]
